1619 Change List Presence Tag indexing
HumanExposure/factotum pull request #2196
Opened 2022-02-24 20:24 UTC by mwfrost

Closes: #1619 

This adds a custom analyzer to the ListPresenceTag indexing code - now each list presence tag name with an underscore is split into multiple tokens, and the search will match any one of the tokens.

2022-02-24 20:31 UTC, mwfrost commented on dashboard/fixtures/14_list_presence_tag.yaml
> +  pk: 374
This was just added for a test

2022-02-25 19:48 UTC, hausman-gdit commented on dashboard/tests/functional/test_search.py
> +        self.assertInHTML('<small class="text-muted pb-4" id="total-took">2 tags returned in 0.001 seconds.</small>', str(found[0]))
specifying seconds to return fails the test (passes when `0.0`), looking for alternatives/checking more into pytest.

2022-02-25 21:18 UTC, hausman-gdit requested changes
Test Fix: specifying seconds to return fails the test (passes when `0.0` for me not `0.001`)

2022-02-28 20:15 UTC, mwfrost commented on dashboard/tests/functional/test_search.py
> +        self.assertInHTML('<small class="text-muted pb-4" id="total-took">2 tags returned in 0.001 seconds.</small>', str(found[0]))
Try `manage.py test dashboard.tests.functional.test_search.TestSearch.test_search_tag` now

2022-02-28 20:20 UTC, hausman-gdit commented on dashboard/tests/functional/test_search.py
> +        found_string = re.sub("\d+.\d+ seconds", "x.x seconds", str(found[0]))
lol clever!

2022-02-28 20:24 UTC, hausman-gdit approved these changes
PR resolves issue, tests pass post-fix

2022-02-28 20:24 UTC, merged